[build]
  publish = "public"
  functions = "netlify/functions" # Certifique-se de que esta linha está correta e na raiz

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200